services:
  database:
    image: postgres:latest
    container_name: booking-service-database
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: booking-service-server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:

volumes:
  database: